name: Formal Verification

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - '**.sol'
  # pull_request:
  #   paths:
  #     - '**.sol'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v6
        with: { 
          python-version: 3.13 
        }

      - name: Install java
        uses: actions/setup-java@v5
        with: { 
          java-version: "11", 
          java-package: jre 
        }

      # It's recommended to pin the latest certora-cli version available in https://pypi.org/project/certora-cli/
      - name: Install certora cli
        run: pip install certora-cli==8.1.1

      - name: Install solc
        run: |
          pip install solc-select
          solc-select install 0.8.31
          solc-select use 0.8.31

      - name: Verify
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
        run: certoraRun src/ERC20/certora/ERC20Harness.conf
