name: Formal Verification

on:
  workflow_dispatch:
  # Commented to reduce github CI time limits
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '**.sol'
  # pull_request:
  #   paths:
  #     - '**.sol'

env:
  CERTORAKEY: ${{ secrets.CERTORAKEY }}

jobs:
  verify:
    runs-on: ubuntu-latest
    # certora config paths
    strategy:
      matrix:
        certora-config-path: [
          "src/openzeppelin/ERC20/certora/ERC20Harness.conf", 
          "src/openzeppelin/ERC721/certora/ERC721Harness.conf"
        ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      # ====================
      # Project Dependencies
      # ====================

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # ====================
      # Certora Dependencies
      # ====================

      - name: Install python
        uses: actions/setup-python@v6
        with: { 
          python-version: 3.13 
        }

      - name: Install java
        uses: actions/setup-java@v5
        with: { 
          java-version: "11", 
          java-package: jre,
          distribution: temurin
        }

      # It's recommended to pin the latest certora-cli version available in https://pypi.org/project/certora-cli/
      - name: Install certora cli
        run: pip install certora-cli==8.3.1

      - name: Install solc
        run: |
          pip install solc-select
          solc-select install 0.8.30
          solc-select use 0.8.30

      # ===============
      # Verify contract
      # ===============
      - name: Verify
        run: certoraRun ${{ matrix.certora-config-path }}
